name: Deploy Android build Google Play internal testing

on:
  push:
    branches:
      - master
    paths:
      - android/app/build.gradle

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        run: |
          yarn --frozen-lockfile

      - name: Prepare singing configuration
        run: |
          mkdir -p $HOME/.gradle

          printf "\
          ZBAY_UPLOAD_STORE_FILE=zbaymobile.keystore\n\
          ZBAY_UPLOAD_KEY_ALIAS=${{ SECRETS.GOOGLE_KEYSTORE_ALIAS }}\n\
          ZBAY_UPLOAD_STORE_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\n\
          ZBAY_UPLOAD_KEY_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\
          " > $HOME/.gradle/gradle.properties

          echo ${{ SECRETS.GOOGLE_KEYSTORE }} | base64 --decode > android/app/zbaymobile.keystore

      - name: Build for Android
        run: cd android && ./gradlew assembleRelease

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: ./android/app/build/outputs/apk/release/app-release.apk
          retention-days: 5

      - name: Configure Google Pay upload
        run: |
          mkdir -p distribution/whatsnew
          git log -1 --pretty=format:%s > distribution/whatsnew/whatsnew-pl-PL
          echo ${{ SECRETS.SERVICE_ACCOUNT_JSON }} | base64 --decode > google-play.json

      - name: 'Upload to Google Play'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google-play.json
          packageName: com.zbaymobile
          releaseFiles: ./android/app/build/outputs/apk/release/app-release.apk
          track: internal
          whatsNewDirectory: distribution/whatsnew
