name: End to end tests

on:
  pull_request:
    branches: ['*']
  push:
    branches: [ master, develop ]

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # "macos-latest" UnableToAccessScreenRecordingAPIError: The find-window process cannot access the Screen Recording API. https://github.com/DevExpress/testcafe/issues/5352
        os: [ubuntu-20.04, windows-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install project dependencies
        run: npm ci
      - name: Build project
        run: npm run build:prod
      - name: Run tests
        env:
          E2E_TEST: true
          NODE_ENV: development
          DEBUG: 'waggle*,zbay*,testcafe*electron*'
        uses: DevExpress/testcafe-action@latest
        with:
          skip-install: true
          args: "--color --hostname localhost -p '${DATE}_${TIME}_${TEST_ID}.png' -S --screenshots-full-page --selector-timeout 10000 \"electron:.\" \"./**/*.e2e.ts\""
      - name: Print current working directory and files
        if: failure() && matrix.os == 'ubuntu-20.04'
        run: pwd && ls -alh && ls screenshots
      - name: Archive test screenshots  # Taking screenshots doesn't work right now on CI
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-screenshots
          path: ${{ github.workspace }}/screenshots/*.png
