name: Deploy Android to Google Play (internal testing)

on:
  release:
    types: 
      [released, prereleased]

jobs:
  build-android:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    if: |
      startsWith(github.ref, 'refs/tags/@quiet/mobile')

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v2

      - name: "Set up JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Set up NDK"
        run: |
          mkdir /usr/lib/android-sdk
          cd /usr/lib/android-sdk
          yes | wget -c https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Create gradle configuration directory"
        run: mkdir -p $HOME/.gradle
      
      - name: "Prepare signing configuration"
        run: |
          printf "\
          STORE_FILE=quietmobile.keystore\n\
          STORE_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\n\
          KEY_ALIAS=${{ SECRETS.GOOGLE_KEYSTORE_ALIAS }}\n\
          KEY_PASSWORD=${{ SECRETS.GOOGLE_KEYSTORE_PASSWORD }}\
          " > $HOME/.gradle/gradle.properties

      - name: "Decode keystore"
        run: echo ${{ SECRETS.GOOGLE_KEYSTORE }} | base64 --decode > ./packages/mobile/android/app/quietmobile.keystore

      - name: "Build for Android"
        run: cd ./packages/mobile/android && ./gradlew bundleRelease

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: ./packages/mobile/android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 5

      - name: "Configure Google Play upload"
        run: |
          mkdir -p distribution/whatsnew
          git log -1 --pretty=format:%s > distribution/whatsnew/whatsnew-pl-PL
          echo ${{ SECRETS.SERVICE_ACCOUNT_JSON }} | base64 --decode > google-play.json
      
      - name: "Upload to Google Play"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google-play.json
          packageName: com.zbaymobile
          releaseFiles: ./packages/mobile/android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: distribution/whatsnew
