name: E2E linux

on: [workflow_call]
jobs:

  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    timeout-minutes: 180

    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      DISPLAY: ":99.0"
      TEST_MODE: true
      ELECTRON_ENABLE_LOGGING: true

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install WM
        run: sudo apt install fluxbox

      - name: Install libfuse2
        run: sudo apt install libfuse2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-linux"
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/desktop,backend-bundle,e2e-tests"

      - name: Run X11
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          fluxbox &

      - name: Build App Image
        working-directory: ./packages/desktop
        run: npm run distUbuntu && VERSION=$(jq -r ".version" package.json) && cd dist && FILE_NAME=$(ls | grep $VERSION) && echo "FILE_NAME=$(ls | grep $VERSION)" >> $GITHUB_ENV && cp $FILE_NAME ../../e2e-tests/Quiet && export FILE_NAME=$FILE_NAME

      - name: Chmod
        working-directory: ./packages/e2e-tests/Quiet
        run: chmod +x $FILE_NAME

      - name: Run one client test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test oneClient.test.ts

      - name: Run multiple clients test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test multipleClients.test.ts

      - name: Run user profile test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test userProfile.test.ts

      - name: Run invitation link test - Includes 2 separate application clients
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 25
          max_attempts: 1
          command: cd packages/e2e-tests && npm run test invitationLink.test.ts

      - name: Run Backwards Compatibility test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: cd packages/e2e-tests && npm run test backwardsCompatibility.test.ts
