name: E2E Windows

on: [workflow_call]
jobs:
  windows:
    runs-on: windows-2019

    timeout-minutes: 180

    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      TEST_MODE: true
      E2E: true
      ELECTRON_ENABLE_LOGGING: true

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-windows"
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,@quiet/desktop,backend-bundle,e2e-tests"

      - name: "Fetch jsign"
        shell: bash
        run: cd packages/desktop && curl https://zbay-binaries.s3.us-east-2.amazonaws.com/jsign/jsign-2.1.jar --output ./jsign-2.1.jar

      - name: "Remove test files workaround (jest types conflicting with cypress types)"
        run: find packages/desktop/src -name '*.test.*' -delete
        shell: bash

      - name: Before build
        uses: ./.github/actions/before-build
        with:
          source-path: win32

      - name: electron-builder
        working-directory: ./packages/desktop
        run: node_modules/.bin/electron-builder --win
        shell: bash

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@fdb5b74adc1278ddb777dfed4c988b9d098bb48d # v1.2.1
        with:
          path: packages/desktop

      - name: FILE_NAME env
        working-directory: ./packages/desktop/dist
        run: echo "FILE_NAME=Quiet Setup ${{ steps.extract_version.outputs.version }}.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Chmod
        working-directory: ./packages/desktop/dist
        run: chmod +x "$FILE_NAME"
        shell: bash

      - name: "Upload built app"
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: quiet-windows
          path: ./packages/desktop/dist/Quiet Setup ${{ steps.extract_version.outputs.version }}.exe
          retention-days: 2

      - name: Install exe
        run: Start-Process "Quiet Setup ${{ steps.extract_version.outputs.version }}.exe" -Wait
        working-directory: ./packages/desktop/dist
        shell: powershell

      - name: Check if Quiet installed properly
        run: Get-ChildItem -Path C:\Users\runneradmin\AppData\Local\Programs\@quietdesktop
        shell: powershell

      - name: Kill Quiet
        run: Get-Process -Name "Quiet" -ErrorAction SilentlyContinue | Stop-Process -Force
        shell: powershell
        if: always()

      - name: Kill tor
        run: Get-Process -Name "tor" -ErrorAction SilentlyContinue | Stop-Process -Force
        shell: powershell

      - name: Delay
        run: Start-Sleep -Seconds 10
        shell: powershell

      - name: Run one client test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 15
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test oneClient.test.ts

      - name: Run multiple clients test
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test multipleClients.test.ts

      - name: Run user profile test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test userProfile.test.ts

      - name: Run invitation link test - Includes 2 separate application clients
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2.9.0
        with:
          timeout_minutes: 25
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test invitationLink.test.ts
