name: E2E cross platform

on: [pull_request]
jobs:
  mac:
    uses: ./.github/workflows/e2e-mac.yml
  linux:
    uses: ./.github/workflows/e2e-linux.yml
  windows:
    runs-on: windows-2019
    timeout-minutes: 180
    env:
      ELECTRON_CUSTOM_VERSION: 23.0.0
      TEST_MODE: true

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          cachePrefix: "e2e-crossplatform-windows"
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/common,@quiet/types,@quiet/state-manager,@quiet/backend,@quiet/identity,quiet,backend-bundle,e2e-tests"

      - name: "Fetch jsign"
        shell: bash
        run: cd packages/desktop && curl https://zbay-binaries.s3.us-east-2.amazonaws.com/jsign/jsign-2.1.jar --output ./jsign-2.1.jar


      - name: "Add Windows certificate"
        id: write_file
        uses: TryQuiet/base64-to-file@main
        with:
          fileName: 'win-certificate.pfx'
          encodedString: ${{ secrets.WIN_CSC_LINK }}

      - name: "Remove test files workaround (jest types conflicting with cypress types)"
        run: find packages/desktop/src -name '*.test.*' -delete
        shell: bash

      - name: Before build
        uses: ./.github/actions/before-build
        with:
          source-path: win32

      - name: electron-builder
        env:
          CERTIFICATE_PATH: ${{ steps.write_file.outputs.filePath }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          WINDOWS_ALIAS: ${{ secrets.WIN_ALIAS }}
        working-directory: ./packages/desktop
        run: node_modules/.bin/electron-builder --win 
        shell: bash

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1
        with:
          path: packages/desktop

      - name: FILE_NAME env
        working-directory: ./packages/desktop/dist
        run: echo "FILE_NAME=Quiet Setup ${{ steps.extract_version.outputs.version }}.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        shell: powershell

      - name: Chmod
        working-directory: ./packages/desktop/dist
        run: chmod +x "$FILE_NAME"
        shell: bash

      - name: "Upload built app"
        uses: actions/upload-artifact@v2
        with:
          name: quiet-windows
          path: ./packages/desktop/dist/Quiet Setup ${{ steps.extract_version.outputs.version }}.exe
          retention-days: 2

      - name: Install exe
        run: Start-Process "Quiet Setup ${{ steps.extract_version.outputs.version }}.exe" -Wait
        working-directory: ./packages/desktop/dist
        shell: powershell

      - name: Kill Quiet
        run: Stop-Process -Name "Quiet" -Force
        shell: powershell

      - name: Kill tor
        run: Stop-Process -Name "tor" -Force
        shell: powershell

      - name: Delay
        run: Start-Sleep -Seconds 10
        shell: powershell

      - name: Run one client test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test oneClient.test.ts

      - name: Run two clients test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test twoClients.test.ts

      - name: Run invitation link test - Includes 2 separate application clients
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 25
          max_attempts: 3
          shell: bash
          command: cd packages/e2e-tests && npm run test invitationLink.test.ts
      #   # Old prod version
      # - name: Rename latest quiet
      #   run: cd $env:LOCALAPPDATA/programs; rename-item quiet quiet2
      #   shell: powershell

      # - name: Download EXE
      #   run: curl -LO https://github.com/TryQuiet/quiet/releases/download/quiet%401.2.0/Quiet.Setup.1.2.0.exe
      #   shell: bash

      # - name: Chmod
      #   run: chmod +x Quiet.Setup.1.2.0.exe
      #   shell: bash

      # - name: Install exe
      #   run: Start-Process Quiet.Setup.1.2.0.exe -Wait
      #   shell: powershell

      # - name: Kill Quiet
      #   run: Stop-Process -Name "Quiet" -Force
      #   shell: powershell

      # - name: Kill tor
      #   run: Stop-Process -Name "tor" -Force
      #   shell: powershell

      # - name: Delay
      #   run: Start-Sleep -Seconds 10
      #   shell: powershell
      #   # Old prod version

      # - name: Run Backwards Compatibility test
      #   working-directory: ./packages/e2e-tests
      #   run: npm run test backwardsCompatibility.test.ts

