name: Common package tests

on:
  pull_request:
    paths:
      - packages/common/**

jobs:
  utils-tests:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Setup environment"
        uses: ./.github/actions/setup-env
        with:
          bootstrap-packages: "@quiet/eslint-config,@quiet/logger,@quiet/types,@quiet/common"

      - name: "Unit tests"
        run: lerna run test --scope @quiet/common --stream
