name: Waggle unit tests

on:
  pull_request:
    paths:
      - packages/waggle/**

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}
      
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Unit tests"
        run: lerna run test-ci --scope @quiet/waggle --stream

  unit-tests-with-tor:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}
      
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: "Unit tests"
        run: lerna run test-ci-tor --scope @quiet/waggle --stream
