name: Node connections test

on:
  pull_request:
    paths:
      - packages/waggle/**

jobs:
  test-connect:
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    
    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: run tests
        run: lerna run test-connect-ci --scope @quiet/waggle --stream

  test-replicate:
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: Install ts-node globally
        run: npm install --global ts-node

      - name: run test without tor
        run: lerna run test-replication-no-tor --scope @quiet/waggle --stream

      - name: run test with tor
        run: lerna run test-replication-tor --scope @quiet/waggle --stream
