name: Node connections test

on:
  pull_request:
    paths:
      - packages/waggle/**

jobs:
  test-connect:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    
    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: run tests
        run: lerna run test-connect-ci --scope waggle --stream

  test-replicate:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: "Setup environment"
        uses: ./.github/actions/setup-env

      - name: run test without tor
        run: lerna run test-replication-no-tor --scope waggle --stream

      - name: run test with tor
        run: lerna run test-replication-tor --scope waggle --stream
