name: Zbay tests

on:
  pull_request:
    paths:
      - packages/ZbayLite

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:
      - name: "Print OS"
        run: echo ${{ matrix.os }}

      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-node@master
        with:
          node-version: "12"

      - name: "Patch node gyp on windows to support Visual Studio 2019"
        if: ${{ matrix.os == 'windows-latest' }}
        shell: powershell
        run: |
          npm install --global node-gyp@latest
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}
          npm config set msvs_version 2019

      - name: "Get extra dependencies"
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm install -g windows-build-tools@4.0.0

      - name: "Set unsafe-perm"
        run: npm set unsafe-perm true

      - name: "Install lerna globally"
        run: npm i -g lerna

      - name: "Cache NPM dependencies"
        uses: actions/cache@v1
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: "Install monorepo dependencies"
        run: npm ci

      - name: "Bootstrap project"
        run: lerna bootstrap

      - name: "Unit tests"
        run: lerna run test --scope zbay --stream

      - name: "Zbay-nectar bracket tests"
        run: lerna run rtl-test --scope zbay --stream 
